# Generated by Django 4.0.4 on 2022-04-14 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management_app', '0002_remove_events_participants_maybe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='profiles_images/default_user_icon.svg', upload_to='profiles_images', verbose_name='Zdjęcie')),
                ('nick_name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Ksywa')),
                ('best_place', models.CharField(blank=True, max_length=20, verbose_name='Ulubione miejsce')),
                ('lead_replica', models.CharField(blank=True, max_length=50, verbose_name='Replika główna')),
                ('additional_replica', models.CharField(blank=True, max_length=50, verbose_name='Replika dodatkowa')),
                ('side_replica', models.CharField(blank=True, max_length=50, verbose_name='Replika boczna')),
                ('gear', models.TextField(blank=True, verbose_name='Wyposażenie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
