# Generated by Django 4.0.4 on 2022-04-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0004_alter_events_event_image_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Zdjęcie'),
        ),
    ]
