# Generated by Django 4.0.4 on 2022-04-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0005_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, default='events_images/default_event_icon.svg', null=True, upload_to='events_images/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles_images/', verbose_name='Zdjęcie'),
        ),
    ]
