# Generated by Django 4.0.4 on 2022-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0006_alter_events_event_image_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles_images/default_profile_icon.svg', null=True, upload_to='profiles_images/', verbose_name='Zdjęcie'),
        ),
    ]
