# Generated by Django 4.0.4 on 2022-04-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0007_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='title2',
        ),
    ]
