# Generated by Django 4.0.4 on 2022-04-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0012_alter_offers_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='offer_image',
            field=models.ImageField(blank=True, default='offers_images/default_offer_icon.svg', upload_to='offers_images/', verbose_name='Zdjęcie'),
        ),
    ]
