# Generated by Django 4.0.4 on 2022-04-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0017_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='offer_image',
            new_name='post_image',
        ),
    ]
