# Generated by Django 4.0.4 on 2022-04-26 10:06

import custom.picture_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0019_alter_profile_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(verbose_name='Dodaj komentarz'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_image',
            field=models.ImageField(blank=True, default='offers_images/default_offer_icon.svg', upload_to='offers_images/', validators=[custom.picture_size.picture_size], verbose_name='Zdjęcie'),
        ),
    ]
