# Generated by Django 4.0.4 on 2022-04-26 11:27

import custom.picture_size
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0020_alter_comment_description_alter_offers_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Dodaj komentarz'),
        ),
        migrations.AlterField(
            model_name='events',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, default='events_images/default_event_icon.svg', null=True, upload_to='events_images/', validators=[custom.picture_size.picture_size], verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='posts_images/default_post_icon.svg', upload_to='posts_images/', validators=[custom.picture_size.picture_size], verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gear',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Wyposażenie'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles_images/default_profile_icon.svg', null=True, upload_to='profiles_images/', validators=[custom.picture_size.picture_size], verbose_name='Zdjęcie'),
        ),
    ]
