# Generated by Django 4.0.4 on 2022-04-27 11:10

import custom.picture_size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_app', '0023_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='events_images/', validators=[custom.picture_size.picture_size], verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offer_image',
            field=models.ImageField(blank=True, null=True, upload_to='offers_images/', validators=[custom.picture_size.picture_size], verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts_images/', validators=[custom.picture_size.picture_size], verbose_name='Zdjęcie'),
        ),
    ]
